#theme: minimal-mistakes-jekyll  # 또는 remote_theme
remote_theme: mmistakes/minimal-mistakes

title: "nnn Blog"
name: "nnn"
description: "이 블로그는 보안과 관련하여 기록하는 어쩌고저쩌고"

# 프로필 사진 경로 (assets/images/에 넣을 사진)
logo: "/assets/images/profile.jpg"

# 다크 테마
minimal_mistakes_skin: "dark"

# 상단 네비게이션
navigation:
  - title: "Home"
    url: /
  - title: "Category"
    url: /#category
  - title: "Post"
    url: /#posts
  - title: "about"
    url: /about/

head_scripts:
  - /assets/css/custom.css
  
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache
